In [1]:
import pandas as pd
import numpy as np

Creating a Pandas Dataframe

In [5]:
#Creating an empty Dataframe
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [6]:
#Creating a DataFrame from a list
lst = ['Geeks', 'For', 'Geeks', 'is', 
            'portal', 'for', 'Geeks']

df = pd.DataFrame(lst)
print(df)

        0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [7]:
#Creating Dataframe from dict of Numpy array
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(data, columns=['A', 'B', 'C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [8]:
#Creating a Datframe from a list of dictionaries
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}

df = pd.DataFrame(dict)
print(df)

     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

In [9]:
#Creating a Dataframe from lists or arrays
# initialize list of lists
data = [['tom', 10], ['nick', 15], ['juli', 14]]

# Create the pandas DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age'])

print(df)

   Name  Age
0   tom   10
1  nick   15
2  juli   14

In [11]:
#Creating Dataframe from a list of dictionaries

# Initialize data to lists.
data = [{'a': 1, 'b': 2, 'c': 3},
        {'a': 10, 'b': 20, 'c': 30},
       {'a':100, 'b':200, 'c':300}]

# Creates DataFrame.
df = pd.DataFrame(data)

print(df)

     a    b    c
0    1    2    3
1   10   20   30
2  100  200  300

In [12]:
#Another example is to create a Pandas DataFrame by passing lists of dictionaries and row indexes.
# Initialize data of lists
data = [{'b': 2, 'c': 3}, {'a': 10, 'b': 20, 'c': 30}]

# Creates pandas DataFrame by passing
# Lists of dictionaries and row index.
df = pd.DataFrame(data, index=['first', 'second'])
print(df)

         b   c     a
first    2   3   NaN
second  20  30  10.0

In [13]:
#Creating a DataFrame from Another DataFrame
original_df = pd.DataFrame({
    'Name': ['Tom', 'Nick', 'Krish', 'Jack'],
    'Age': [20, 21, 19, 18]
})

new_df = original_df[['Name']] 
print(new_df)

    Name
0    Tom
1   Nick
2  Krish
3   Jack

In [14]:
#Create DataFrame from a Dictionary of Series
# Initialize data to Dicts of series.
d = {'one': pd.Series([10, 20, 30, 40],
                      index=['a', 'b', 'c', 'd']),
     'two': pd.Series([10, 20, 30, 40],
                      index=['a', 'b', 'c', 'd'])}

# creates Dataframe.
df = pd.DataFrame(d)

print(df)

   one  two
a   10   10
b   20   20
c   30   30
d   40   40

In [46]:
#Create a Dataframe by providing the index label explicitly
# List1
Name = ['tom', 'krish', 'nick', 'juli']

# List2
Age = [25, 30, 26, 22]

# get the list of tuples from two lists.
# and merge them by using zip().
list_of_tuples = list(zip(Name, Age))

# Assign data to tuples.
list_of_tuples


# Converting lists of tuples into
# pandas Dataframe.
df = pd.DataFrame(list_of_tuples,
                  columns=['Name', 'Age'])

print(df)

    Name  Age
0    tom   25
1  krish   30
2   nick   26
3   juli   22

In [69]:
Students = ['Koketso', 'Lesedi', 'Laetitia', 'Nikki']
Course = ['BscIT', 'BBA', 'BCOM', 'LLB']

merge = list(zip(Students, Course))

df = pd.DataFrame(merge, columns=['Students', 'Course'])
print(df)

   Students Course
0   Koketso  BscIT
1    Lesedi    BBA
2  Laetitia   BCOM
3     Nikki    LLB

In [16]:
#Create a DataFrame by Proving the Index Label Explicitly
# initialize data of lists.
data = {'Name': ['Tom', 'Jack', 'nick', 'juli'],
        'marks': [99, 98, 95, 90]}

# Creates pandas DataFrame.
df = pd.DataFrame(data, index=['rank1',
                               'rank2',
                               'rank3',
                               'rank4'])

# print the data
print(df)

       Name  marks
rank1   Tom     99
rank2  Jack     98
rank3  nick     95
rank4  juli     90

Python Pandas Series

In [17]:
#Creating a Pandas Series
data = [1, 2, 3, 4]
 
ser = pd.Series(data)
print(ser)

0    1
1    2
2    3
3    4
dtype: int64

In [23]:
#Accessing elements of Series
#1. Position-based Indexing
print(" Position-based Indexing")
data = np.array(['g','e','e','k','s','f', 'o','r','g','e','e','k','s'])
ser = pd.Series(data)

print(ser[:5])

print(ser[5:8])
print("\n")

#2. Label-based Indexing
print("Label-based Indexing")
data = np.array(['g','e','e','k','s','f', 'o','r','g','e','e','k','s'])
ser = pd.Series(data,index=[10,11,12,13,14,15,16,17,18,19,20,21,22])

print(ser)
print(ser[16])
print(ser[10])

 Position-based Indexing
0    g
1    e
2    e
3    k
4    s
dtype: object
5    f
6    o
7    r
dtype: object


Label-based Indexing
10    g
11    e
12    e
13    k
14    s
15    f
16    o
17    r
18    g
19    e
20    e
21    k
22    s
dtype: object
o
g

In [31]:
#Indexing and Selecting Data in Series
#1. Indexing a Series using .loc[]
print("Indexing a Series using .loc[]")
df = pd.read_csv(r"C:\Users\gonts\OneDrive - Richfield Graduate Institute of Technology\HR_Data_MNC_Data Science Lovers.csv")  
   
print(df.head())

Indexing a Series using .loc[]
   Unnamed: 0 Employee_ID        Full_Name  Department              Job_Title  \
0           0  EMP0000001    Joshua Nguyen          IT      Software Engineer
1           1  EMP0000002   Julie Williams   Marketing         SEO Specialist
2           2  EMP0000003  Alyssa Martinez          HR             HR Manager
3           3  EMP0000004  Nicholas Valdez          IT      Software Engineer
4           4  EMP0000005   Joel Hendricks  Operations  Logistics Coordinator

    Hire_Date                                 Location  Performance_Rating  \
0  2011-08-10                       Isaacland, Denmark                   5
1  2018-03-02                  Anthonyside, Costa Rica                   2
2  2023-03-20         Port Christinaport, Saudi Arabia                   1
3  2023-10-12  Port Shelbychester, Antigua and Barbuda                   1
4  2024-12-09     Lake Kimberly, Palestinian Territory                   5

   Experience_Years    Status Work_Mode  Salary_INR
0                14  Resigned   On-site     1585363
1                 7    Active   On-site      847686
2                 2    Active   On-site     1430084
3                 1    Active   On-site      990689
4                 0    Active   On-site      535082

In [33]:
#Indexing and Selecting Data in Series
#1. Indexing a Series using .loc[]
print("Indexing a Series using .loc[]")
df = pd.read_csv(r"C:\Users\gonts\OneDrive - Richfield Graduate Institute of Technology\HR_Data_MNC_Data Science Lovers.csv")  

ser = pd.Series(df['Full_Name'])
data = ser.head(10)
data
data.iloc[3:6]

Indexing a Series using .loc[]

3    Nicholas Valdez
4     Joel Hendricks
5      Jason Gardner
Name: Full_Name, dtype: object

In [34]:
#Binary Operations on Pandas Series
ser1 = pd.Series([1, 2, 3], index=['A', 'B', 'C'])
ser2 = pd.Series([4, 5, 6], index=['A', 'B', 'C'])

df_sum = ser1.add(ser2)
print(df_sum)

A    5
B    7
C    9
dtype: int64

In [35]:
#Conversion Operation on Series
ser = pd.Series([1, 2, 3, 4])
ser = ser.astype(float)
print(ser)

0    1.0
1    2.0
2    3.0
3    4.0
dtype: float64

In [36]:
#Creating a Pandas Series
#Creating an Empty Pandas Series
ser = pd.Series()
print(ser)

Series([], dtype: object)

In [37]:
#Creating a Series from a NumPy Array
data = np.array(['g', 'e', 'e', 'k', 's'])

ser = pd.Series(data)
print(ser)

0    g
1    e
2    e
3    k
4    s
dtype: object

In [38]:
#Creating a Series from a Dictionary
data_dict = {'Geeks': 10, 'for': 20, 'geeks': 30}

ser = pd.Series(data_dict)
print(ser)

Geeks    10
for      20
geeks    30
dtype: int64

In [39]:
#Creating a Series Using NumPy Functions
ser = pd.Series(np.linspace(1, 10, 5))
print(ser)

0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64

In [40]:
#Creating a Series Using range()
ser = pd.Series(range(5, 15))
print(ser)

0     5
1     6
2     7
3     8
4     9
5    10
6    11
7    12
8    13
9    14
dtype: int64

In [41]:
#Creating a Series Using List Comprehension
ser=pd.Series(range(1,20,3), index=[x for x in 'abcdefg'])
print(ser)

a     1
b     4
c     7
d    10
e    13
f    16
g    19
dtype: int64

Pandas Dataframe/Series.head() method - Python

In [42]:
#using head() on a DataFrame
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")

print("NBA Dataset (First 5 Rows):")
print(data.head())

NBA Dataset (First 5 Rows):
            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

In [43]:
#Using head() with a Custom Number of Rows
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")

series = data["Name"]

top = series.head(n = 7)

print("NBA Dataset (First 7 Rows):")
print(top)

NBA Dataset (First 7 Rows):
0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
6    Jordan Mickey
Name: Name, dtype: object

In [45]:
#Using head() on a Series
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")

salary = data['Salary']

print("First 5 Salaries:")
print(salary.head())

First 5 Salaries:
0    7730337.0
1    6796117.0
2          NaN
3    1148640.0
4    5000000.0
Name: Salary, dtype: float64

In [47]:
#Describing Specific Columns with head()
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")

salary_name = data[['Name', 'Salary']].head()

print("First 5 Rows of Name and Salary Columns:")
print(salary_name)

First 5 Rows of Name and Salary Columns:
            Name     Salary
0  Avery Bradley  7730337.0
1    Jae Crowder  6796117.0
2   John Holland        NaN
3    R.J. Hunter  1148640.0
4  Jonas Jerebko  5000000.0

In [48]:
#Using head() After Sorting a DataFrame
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")

sorted_data = data.sort_values(by='Age', ascending=True)

top_sorted = sorted_data.head()

print("First 5 Rows After Sorting by Age:")
print(top_sorted)

First 5 Rows After Sorting by Age:
                   Name                    Team  Number Position   Age Height  \
226       Rashad Vaughn         Milwaukee Bucks    20.0       SG  19.0    6-6
122        Devin Booker            Phoenix Suns     1.0       SG  19.0    6-6
40   Kristaps Porzingis         New York Knicks     6.0       PF  20.0    7-3
401          Tyus Jones  Minnesota Timberwolves     1.0       PG  20.0    6-2
427     Cliff Alexander  Portland Trail Blazers    34.0       PF  20.0    6-8

     Weight   College     Salary
226   202.0      UNLV  1733040.0
122   206.0  Kentucky  2127840.0
40    240.0       NaN  4131720.0
401   195.0      Duke  1282080.0
427   240.0    Kansas   525093.0

Pandas Dataframe/Series.tail() method - Python

In [50]:
#Using tail() on a DataFrame
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")

print("NBA Dataset (Last 5 Rows):")
print(data.tail())

NBA Dataset (Last 5 Rows):
             Name       Team  Number Position   Age Height  Weight College  \
453  Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler
454     Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN
455  Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN
456   Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas
457           NaN        NaN     NaN      NaN   NaN    NaN     NaN     NaN

        Salary
453  2433333.0
454   900000.0
455  2900000.0
456   947276.0
457        NaN

In [51]:
#Using tail() with a Custom Number of Rows
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")

series = data["Name"]

bottom = series.tail(n = 7)

print("NBA Dataset (Last 7 Rows):")
print(bottom)

NBA Dataset (Last 7 Rows):
451    Chris Johnson
452       Trey Lyles
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, dtype: object

In [52]:
#Using tail() on a Series
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")

salary = data['Salary']

print("Last 5 Salaries:")
print(salary.tail())

Last 5 Salaries:
453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
457          NaN
Name: Salary, dtype: float64

In [53]:
#Describing Specific Columns with tail()
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")

salary_name = data[['Name', 'Salary']].tail()

print("Last 5 Rows of Name and Salary Columns:")
print(salary_name)

Last 5 Rows of Name and Salary Columns:
             Name     Salary
453  Shelvin Mack  2433333.0
454     Raul Neto   900000.0
455  Tibor Pleiss  2900000.0
456   Jeff Withey   947276.0
457           NaN        NaN

In [56]:
#Using tail() After Sorting a DataFrame
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")

sorted_data= data.sort_values(by=['Name', 'Salary'], ascending=False)
bottom_sorted = sorted_data.tail()

print("Last 5 Rows After Sorting by Age:")
print(bottom_sorted)

Last 5 Rows After Sorting by Age:
               Name                    Team  Number Position   Age Height  \
404   Adreian Payne  Minnesota Timberwolves    33.0       PF  25.0   6-10
328  Aaron Harrison       Charlotte Hornets     9.0       SG  21.0    6-6
356    Aaron Gordon           Orlando Magic     0.0       PF  20.0    6-9
152    Aaron Brooks           Chicago Bulls     0.0       PG  31.0    6-0
457             NaN                     NaN     NaN      NaN   NaN    NaN

     Weight         College     Salary
404   237.0  Michigan State  1938840.0
328   210.0        Kentucky   525093.0
356   220.0         Arizona  4171680.0
152   161.0          Oregon  2250000.0
457     NaN             NaN        NaN

Pandas Dataframe describe() Method

In [57]:
#Using describe() on a DataFrame
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")

print("NBA Dataset:")
print(data.head())

print("\nSummary Table Generated by .describe() Method:")
print(data.describe())

NBA Dataset:
            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

Summary Table Generated by .describe() Method:
           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07

In [58]:
#Customizing describe() with percentiles
percentiles = [.20, .40, .60, .80]
include = ['object', 'float', 'int']

desc = data.describe(percentiles=percentiles, include=include)

print(desc)

                 Name                  Team      Number Position         Age  \
count             457                   457  457.000000      457  457.000000
unique            457                    30         NaN        5         NaN
top     Avery Bradley  New Orleans Pelicans         NaN       SG         NaN
freq                1                    19         NaN      102         NaN
mean              NaN                   NaN   17.678337      NaN   26.938731
std               NaN                   NaN   15.966090      NaN    4.404016
min               NaN                   NaN    0.000000      NaN   19.000000
20%               NaN                   NaN    4.000000      NaN   23.000000
40%               NaN                   NaN   10.000000      NaN   25.000000
50%               NaN                   NaN   13.000000      NaN   26.000000
60%               NaN                   NaN   18.600000      NaN   27.000000
80%               NaN                   NaN   30.000000      NaN   30.000000
max               NaN                   NaN   99.000000      NaN   40.000000

       Height      Weight   College        Salary
count     457  457.000000       373  4.460000e+02
unique     18         NaN       118           NaN
top       6-9         NaN  Kentucky           NaN
freq       59         NaN        22           NaN
mean      NaN  221.522976       NaN  4.842684e+06
std       NaN   26.368343       NaN  5.229238e+06
min       NaN  161.000000       NaN  3.088800e+04
20%       NaN  195.600000       NaN  9.472760e+05
40%       NaN  213.400000       NaN  1.938840e+06
50%       NaN  220.000000       NaN  2.839073e+06
60%       NaN  230.000000       NaN  3.815000e+06
80%       NaN  245.000000       NaN  8.042895e+06
max       NaN  307.000000       NaN  2.500000e+07

In [59]:
#Describing string(object) Data
desc = data["Name"].describe()
print(desc)

count               457
unique              457
top       Avery Bradley
freq                  1
Name: Name, dtype: object

In [60]:
#Describing specific columns with describe()
salary_desc = data["Salary"].describe()
print(salary_desc)

count    4.460000e+02
mean     4.842684e+06
std      5.229238e+06
min      3.088800e+04
25%      1.044792e+06
50%      2.839073e+06
75%      6.500000e+06
max      2.500000e+07
Name: Salary, dtype: float64

In [61]:
#Describing Data with include='all'
desc_all = data.describe(include='all')
print(desc_all)

                 Name                  Team      Number Position         Age  \
count             457                   457  457.000000      457  457.000000
unique            457                    30         NaN        5         NaN
top     Avery Bradley  New Orleans Pelicans         NaN       SG         NaN
freq                1                    19         NaN      102         NaN
mean              NaN                   NaN   17.678337      NaN   26.938731
std               NaN                   NaN   15.966090      NaN    4.404016
min               NaN                   NaN    0.000000      NaN   19.000000
25%               NaN                   NaN    5.000000      NaN   24.000000
50%               NaN                   NaN   13.000000      NaN   26.000000
75%               NaN                   NaN   25.000000      NaN   30.000000
max               NaN                   NaN   99.000000      NaN   40.000000

       Height      Weight   College        Salary
count     457  457.000000       373  4.460000e+02
unique     18         NaN       118           NaN
top       6-9         NaN  Kentucky           NaN
freq       59         NaN        22           NaN
mean      NaN  221.522976       NaN  4.842684e+06
std       NaN   26.368343       NaN  5.229238e+06
min       NaN  161.000000       NaN  3.088800e+04
25%       NaN  200.000000       NaN  1.044792e+06
50%       NaN  220.000000       NaN  2.839073e+06
75%       NaN  240.000000       NaN  6.500000e+06
max       NaN  307.000000       NaN  2.500000e+07

Basic Information of Pandas Data

In [68]:
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")

print("First 5 rows:\n", data.head())
print("\n")
print("Last 5 rows:\n", data.tail())
print("\n")
print("5 samples of data:\n",data.sample(5))
print("\n")
print("Shape of the dataset:\n", data.shape)
print("\n")
print("Columns of the dataset:\n", data.columns)
print("\n")
print("Type of Data:\n", data.dtypes)
print("\n")
print("Dataset Information:\n", data.info())
print("\n")
print("Description of dataset:\n", data.describe())
print("\n")
print(data.describe(include='all'))

First 5 rows:
             Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0


Last 5 rows:
              Name       Team  Number Position   Age Height  Weight College  \
453  Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler
454     Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN
455  Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN
456   Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas
457           NaN        NaN     NaN      NaN   NaN    NaN     NaN     NaN

        Salary
453  2433333.0
454   900000.0
455  2900000.0
456   947276.0
457        NaN


5 samples of data:
                 Name                    Team  Number Position   Age Height  \
11     Isaiah Thomas          Boston Celtics     4.0       PG  27.0    5-9
449      Rodney Hood               Utah Jazz     5.0       SG  23.0    6-8
427  Cliff Alexander  Portland Trail Blazers    34.0       PF  20.0    6-8
226    Rashad Vaughn         Milwaukee Bucks    20.0       SG  19.0    6-6
338      Cody Zeller       Charlotte Hornets    40.0        C  23.0    7-0

     Weight     College     Salary
11    185.0  Washington  6912869.0
449   206.0        Duke  1348440.0
427   240.0      Kansas   525093.0
226   202.0        UNLV  1733040.0
338   240.0     Indiana  4204200.0


Shape of the dataset:
 (458, 9)


Columns of the dataset:
 Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')


Type of Data:
 Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB
Dataset Information:
 None


Description of dataset:
            Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07


                 Name                  Team      Number Position         Age  \
count             457                   457  457.000000      457  457.000000
unique            457                    30         NaN        5         NaN
top     Avery Bradley  New Orleans Pelicans         NaN       SG         NaN
freq                1                    19         NaN      102         NaN
mean              NaN                   NaN   17.678337      NaN   26.938731
std               NaN                   NaN   15.966090      NaN    4.404016
min               NaN                   NaN    0.000000      NaN   19.000000
25%               NaN                   NaN    5.000000      NaN   24.000000
50%               NaN                   NaN   13.000000      NaN   26.000000
75%               NaN                   NaN   25.000000      NaN   30.000000
max               NaN                   NaN   99.000000      NaN   40.000000

       Height      Weight   College        Salary
count     457  457.000000       373  4.460000e+02
unique     18         NaN       118           NaN
top       6-9         NaN  Kentucky           NaN
freq       59         NaN        22           NaN
mean      NaN  221.522976       NaN  4.842684e+06
std       NaN   26.368343       NaN  5.229238e+06
min       NaN  161.000000       NaN  3.088800e+04
25%       NaN  200.000000       NaN  1.044792e+06
50%       NaN  220.000000       NaN  2.839073e+06
75%       NaN  240.000000       NaN  6.500000e+06
max       NaN  307.000000       NaN  2.500000e+07

Grouping in Pandas

In [70]:
#Group data by a single key
data1 = {'Name':['Jai', 'Anuj', 'Jai', 'Princi',
                 'Gaurav', 'Anuj', 'Princi', 'Abhi'],
        'Age':[27, 24, 22, 32,
               33, 36, 27, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj',
                   'Jaunpur', 'Kanpur', 'Allahabad', 'Aligarh'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd',
                         'B.Tech', 'B.com', 'Msc', 'MA']}
df = pd.DataFrame(data1)
print(df)


df.groupby('Name')
print(df.groupby('Name').groups)

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1    Anuj   24     Kanpur            MA
2     Jai   22  Allahabad           MCA
3  Princi   32    Kannuaj           Phd
4  Gaurav   33    Jaunpur        B.Tech
5    Anuj   36     Kanpur         B.com
6  Princi   27  Allahabad           Msc
7    Abhi   32    Aligarh            MA
{'Abhi': [7], 'Anuj': [1, 5], 'Gaurav': [4], 'Jai': [0, 2], 'Princi': [3, 6]}

In [71]:
gk = df.groupby('Name') 
gk.first()

        Age  Address Qualification
Name
Abhi     32  Aligarh            MA
Anuj     24   Kanpur            MA
Gaurav   33  Jaunpur        B.Tech
Jai      27   Nagpur           Msc
Princi   32  Kannuaj           Phd

In [2]:
df.groupby(['Name', 'Qualification'])
print(df.groupby(['Name', 'Qualification']).groups)

NameError: name 'df' is not defined

df.groupby('Name')['Age'].sum()

In [74]:
df.groupby(['Name'], sort=False)['Age'].sum()

Name
Jai       49
Anuj      60
Princi    59
Gaurav    33
Abhi      32
Name: Age, dtype: int64

In [75]:
df.groupby('Name').groups

{'Abhi': [7], 'Anuj': [1, 5], 'Gaurav': [4], 'Jai': [0, 2], 'Princi': [3, 6]}

In [76]:
grp = df.groupby('Name')
for name, group in grp:
    print(name)
    print(group)
    print()

Abhi
   Name  Age  Address Qualification
7  Abhi   32  Aligarh            MA

Anuj
   Name  Age Address Qualification
1  Anuj   24  Kanpur            MA
5  Anuj   36  Kanpur         B.com

Gaurav
     Name  Age  Address Qualification
4  Gaurav   33  Jaunpur        B.Tech

Jai
  Name  Age    Address Qualification
0  Jai   27     Nagpur           Msc
2  Jai   22  Allahabad           MCA

Princi
     Name  Age    Address Qualification
3  Princi   32    Kannuaj           Phd
6  Princi   27  Allahabad           Msc

In [77]:
grp = df.groupby(['Name', 'Qualification'])
for name, group in grp:
    print(name)
    print(group)
    print()

('Abhi', 'MA')
   Name  Age  Address Qualification
7  Abhi   32  Aligarh            MA

('Anuj', 'B.com')
   Name  Age Address Qualification
5  Anuj   36  Kanpur         B.com

('Anuj', 'MA')
   Name  Age Address Qualification
1  Anuj   24  Kanpur            MA

('Gaurav', 'B.Tech')
     Name  Age  Address Qualification
4  Gaurav   33  Jaunpur        B.Tech

('Jai', 'MCA')
  Name  Age    Address Qualification
2  Jai   22  Allahabad           MCA

('Jai', 'Msc')
  Name  Age Address Qualification
0  Jai   27  Nagpur           Msc

('Princi', 'Msc')
     Name  Age    Address Qualification
6  Princi   27  Allahabad           Msc

('Princi', 'Phd')
     Name  Age  Address Qualification
3  Princi   32  Kannuaj           Phd

In [78]:
grp = df.groupby('Name')
grp.get_group('Jai')

  Name  Age    Address Qualification
0  Jai   27     Nagpur           Msc
2  Jai   22  Allahabad           MCA

In [79]:
grp = df.groupby(['Name', 'Qualification'])
grp.get_group(('Jai', 'Msc'))

  Name  Age Address Qualification
0  Jai   27  Nagpur           Msc

In [80]:
grp1 = df.groupby('Name')
grp1['Age'].aggregate(np.sum)

C:\Users\gonts\AppData\Local\Temp\ipykernel_23140\4113814000.py:2: FutureWarning: The provided callable <function sum at 0x000001CE9FE6BCE0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1['Age'].aggregate(np.sum)

Name
Abhi      32
Anuj      60
Gaurav    33
Jai       49
Princi    59
Name: Age, dtype: int64

In [81]:
grp1 = df.groupby(['Name', 'Qualification'])
grp1['Age'].aggregate(np.sum)

C:\Users\gonts\AppData\Local\Temp\ipykernel_23140\1932127849.py:2: FutureWarning: The provided callable <function sum at 0x000001CE9FE6BCE0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1['Age'].aggregate(np.sum)

Name    Qualification
Abhi    MA               32
Anuj    B.com            36
        MA               24
Gaurav  B.Tech           33
Jai     MCA              22
        Msc              27
Princi  Msc              27
        Phd              32
Name: Age, dtype: int64

In [82]:
grp = df.groupby('Name')
grp['Age'].agg([np.sum, np.mean, np.std])

C:\Users\gonts\AppData\Local\Temp\ipykernel_23140\3832254242.py:2: FutureWarning: The provided callable <function sum at 0x000001CE9FE6BCE0> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp['Age'].agg([np.sum, np.mean, np.std])
C:\Users\gonts\AppData\Local\Temp\ipykernel_23140\3832254242.py:2: FutureWarning: The provided callable <function mean at 0x000001CE9FE94E00> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp['Age'].agg([np.sum, np.mean, np.std])
C:\Users\gonts\AppData\Local\Temp\ipykernel_23140\3832254242.py:2: FutureWarning: The provided callable <function std at 0x000001CE9FE94F40> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grp['Age'].agg([np.sum, np.mean, np.std])

        sum  mean       std
Name
Abhi     32  32.0       NaN
Anuj     60  30.0  8.485281
Gaurav   33  33.0       NaN
Jai      49  24.5  3.535534
Princi   59  29.5  3.535534

In [86]:
import pandas as pd
data2 = {'Name':['Jai', 'Anuj', 'Jai', 'Princi', 
                 'Gaurav', 'Anuj', 'Princi', 'Abhi'], 
        'Age':[27, 24, 22, 32, 
               33, 36, 27, 32], 
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj',
                   'Jaunpur', 'Kanpur', 'Allahabad', 'Aligarh'], 
        'Qualification':['Msc', 'MA', 'MCA', 'Phd',
                         'B.Tech', 'B.com', 'Msc', 'MA'],
        'Score':[23, 34, 35, 45, 47, 50, 52, 53]} 
df = pd.DataFrame(data2)
grp2 = df.groupby('Name')
sc = lambda x: (x - x.mean()) / x.std() 
grp2['Age'].transform(sc)

0    0.707107
1   -0.707107
2   -0.707107
3    0.707107
4         NaN
5    0.707107
6   -0.707107
7         NaN
Name: Age, dtype: float64

In [88]:
grp2 = df.groupby('Name')
grp2.filter(lambda x: len(x) >= 2)

     Name  Age    Address Qualification  Score
0     Jai   27     Nagpur           Msc     23
1    Anuj   24     Kanpur            MA     34
2     Jai   22  Allahabad           MCA     35
3  Princi   32    Kannuaj           Phd     45
5    Anuj   36     Kanpur         B.com     50
6  Princi   27  Allahabad           Msc     52

In [89]:
df.groupby('Name').agg({'Age': 'sum'})

        Age
Name
Abhi     32
Anuj     60
Gaurav   33
Jai      49
Princi   59

Checking missing values in Pandas

In [91]:
#Using isnull()
#Example 1: Finding Missing Values in a DataFrame

d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

mv = df.isnull()

print(mv)

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [92]:
#Filtering Data Based on Missing Values
d = pd.read_csv(r"C:\Users\gonts\Downloads\employees.csv")

bool_series = pd.isnull(d["Gender"])
missing_gender_data = d[bool_series]
print(missing_gender_data)

    First Name Gender  Start Date Last Login Time  Salary  Bonus %  \
20        Lois    NaN   4/22/1995         7:18 PM   64714    4.934
22      Joshua    NaN    3/8/2012         1:58 AM   90816   18.816
27       Scott    NaN   7/11/1991         6:58 PM  122367    5.218
31       Joyce    NaN   2/20/2005         2:40 PM   88657   12.752
41   Christine    NaN   6/28/2015         1:08 AM   66582   11.308
..         ...    ...         ...             ...     ...      ...
961    Antonio    NaN   6/18/1989         9:37 PM  103050    3.050
972     Victor    NaN   7/28/2006         2:49 PM   76381   11.159
985    Stephen    NaN   7/10/1983         8:10 PM   85668    1.909
989     Justin    NaN   2/10/1991         4:58 PM   38344    3.794
995      Henry    NaN  11/23/2014         6:09 AM  132483   16.655

    Senior Management                  Team
20               True                 Legal
22               True       Client Services
27              False                 Legal
31              False               Product
41               True  Business Development
..                ...                   ...
961             False                 Legal
972              True                 Sales
985             False                 Legal
989             False                 Legal
995             False          Distribution

[145 rows x 8 columns]

In [93]:
#Using isna()
data = {'Nmae': ['Amit', 'Sita', np.nan, 'Raj'],
        'Age': [25, np.nan, 22, 28]}

df = pd.DataFrame(data)
print(df.isna())

    Nmae    Age
0  False  False
1  False   True
2   True  False
3  False  False

In [94]:
#Checking for Non-Missing Values Using notnull()
d = {'Fisrt score': [100, 99, np.nan, 95],
     'Second score': [98, 40, 67, np.nan],
     'Third score': [np.nan, 40, 80, 98]}

df = pd.DataFrame(d)
print(df.notnull())

   Fisrt score  Second score  Third score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [96]:
#Filtering Data with Non-Missing Values
d = pd.read_csv(r"C:\Users\gonts\Downloads\employees.csv")

not_missing = pd.notnull(d['Gender'])
g = d[not_missing]
print(g)

    First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male   8/6/1993        12:42 PM   97308    6.945
1       Thomas    Male  3/31/1996         6:53 AM   61933    4.170
2        Maria  Female  4/23/1993        11:17 AM  130590   11.858
3        Jerry    Male   3/4/2005         1:00 PM  138705    9.340
4        Larry    Male  1/24/1998         4:47 PM  101004    1.389
..         ...     ...        ...             ...     ...      ...
994     George    Male  6/21/2013         5:47 PM   98874    4.479
996    Phillip    Male  1/31/1984         6:30 AM   42392   19.675
997    Russell    Male  5/20/2013        12:39 PM   96914    1.421
998      Larry    Male  4/20/2013         4:45 PM   60500   11.985
999     Albert    Male  5/15/2012         6:24 PM  129949   10.169

    Senior Management                  Team
0                True             Marketing
1                True                   NaN
2               False               Finance
3                True               Finance
4                True       Client Services
..                ...                   ...
994              True             Marketing
996             False               Finance
997             False               Product
998             False  Business Development
999              True                 Sales

[855 rows x 8 columns]

Filling Missing Values in Pandas

In [103]:
#Using fillna()
d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(d)

print("Oridinal Dataframe:\n", df)
print("New Dataframe:\n", df.fillna(0))
print("\n")
forward_fill =df.fillna( method='pad')
backward_fill = df.fillna( method='bfill')

print("Filling missing values with the previous value:\n", forward_fill)
print("Filling missing values with the next value:\n", backward_fill )

Oridinal Dataframe:
    First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0
New Dataframe:
    First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0


Filling missing values with the previous value:
    First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0
Filling missing values with the next value:
    First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

C:\Users\gonts\AppData\Local\Temp\ipykernel_23140\2378804863.py:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  forward_fill =df.fillna( method='pad')
C:\Users\gonts\AppData\Local\Temp\ipykernel_23140\2378804863.py:11: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  backward_fill = df.fillna( method='bfill')

In [104]:
# Fill NaN Values with 'No Gender'
d = pd.read_csv(r"C:\Users\gonts\Downloads\employees.csv")
d['Gender'].fillna('No gender', inplace=True)
d[10:25]

C:\Users\gonts\AppData\Local\Temp\ipykernel_23140\938577774.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  d['Gender'].fillna('No gender', inplace=True)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,No gender,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,No gender,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services

In [110]:
#Usin replace()
data = pd.read_csv(r"C:\Users\gonts\Downloads\employees.csv")
print("Data before replacing missing data:\n", data[10:25])
print("\n")
data.replace(to_replace=np.nan, value=-99)
print("Data after replacing missing data with -99:\n", data)

Data before replacing missing data:
    First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
10     Louise  Female   8/12/1980         9:01 AM   63241   15.132
11      Julie  Female  10/26/1997         3:19 PM  102508   12.637
12    Brandon    Male   12/1/1980         1:08 AM  112807   17.492
13       Gary    Male   1/27/2008        11:40 PM  109831    5.831
14   Kimberly  Female   1/14/1999         7:13 AM   41426   14.543
15    Lillian  Female    6/5/2016         6:09 AM   59414    1.256
16     Jeremy    Male   9/21/2010         5:56 AM   90370    7.369
17      Shawn    Male   12/7/1986         7:45 PM  111737    6.414
18      Diana  Female  10/23/1981        10:27 AM  132940   19.082
19      Donna  Female   7/22/2010         3:48 AM   81014    1.894
20       Lois     NaN   4/22/1995         7:18 PM   64714    4.934
21    Matthew    Male    9/5/1995         2:12 AM  100612   13.645
22     Joshua     NaN    3/8/2012         1:58 AM   90816   18.816
23        NaN    Male   6/14/2012         4:19 PM  125792    5.042
24       John    Male    7/1/1992        10:08 PM   97950   13.873

   Senior Management             Team
10              True              NaN
11              True            Legal
12              True  Human Resources
13             False            Sales
14              True          Finance
15             False          Product
16             False  Human Resources
17             False          Product
18             False  Client Services
19             False          Product
20              True            Legal
21             False        Marketing
22              True  Client Services
23               NaN              NaN
24             False  Client Services


Data after replacing missing data with -99:
     First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male    8/6/1993        12:42 PM   97308    6.945
1       Thomas    Male   3/31/1996         6:53 AM   61933    4.170
2        Maria  Female   4/23/1993        11:17 AM  130590   11.858
3        Jerry    Male    3/4/2005         1:00 PM  138705    9.340
4        Larry    Male   1/24/1998         4:47 PM  101004    1.389
..         ...     ...         ...             ...     ...      ...
995      Henry     NaN  11/23/2014         6:09 AM  132483   16.655
996    Phillip    Male   1/31/1984         6:30 AM   42392   19.675
997    Russell    Male   5/20/2013        12:39 PM   96914    1.421
998      Larry    Male   4/20/2013         4:45 PM   60500   11.985
999     Albert    Male   5/15/2012         6:24 PM  129949   10.169

    Senior Management                  Team
0                True             Marketing
1                True                   NaN
2               False               Finance
3                True               Finance
4                True       Client Services
..                ...                   ...
995             False          Distribution
996             False               Finance
997             False               Product
998             False  Business Development
999              True                 Sales

[1000 rows x 8 columns]

In [112]:
#Dropping Missing Values in Pandas
#Dropping Rows with At Least One Null Value
dict = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, 40, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)

print(df.dropna())

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

In [116]:
#Dropping Rows with All Null Values
dict = {'First Score': [100, np.nan, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, np.nan, 80, 98],
        'Fourth Score': [np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)

df.dropna(how='all')
df.dropna(how='any')

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0         98.0          65.0

In [114]:
#Dropping Columns with At Least One Null Value
dict = {'First Score': [100, np.nan, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score': [52, np.nan, 80, 98],
        'Fourth Score': [60, 67, 68, 65]}
df = pd.DataFrame(dict)

df.dropna(axis=1)

   Fourth Score
0            60
1            67
2            68
3            65

In [115]:
#Dropping Rows with Missing Values in CSV Files
data = pd.read_csv(r"C:\Users\gonts\Downloads\employees.csv")
nd = data.dropna(axis=0, how='any')

print("Old data frame length:", len(data))
print("New data frame length:", len(nd))
print("Rows with at least one missing value:", (len(data) - len(nd)))

Old data frame length: 1000
New data frame length: 764
Rows with at least one missing value: 236

In [117]:
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")
#describing specific columns with head()
salary_name = data[['Name', 'Salary']].head()
print(salary_name)

            Name     Salary
0  Avery Bradley  7730337.0
1    Jae Crowder  6796117.0
2   John Holland        NaN
3    R.J. Hunter  1148640.0
4  Jonas Jerebko  5000000.0

In [118]:
#describing string (object) data
desc = data['Name'].describe()
print(desc)

count               457
unique              457
top       Avery Bradley
freq                  1
Name: Name, dtype: object

In [119]:
#describing data with include='all'
desc_all = data.describe(include='all')
print(desc_all)

                 Name                  Team      Number Position         Age  \
count             457                   457  457.000000      457  457.000000
unique            457                    30         NaN        5         NaN
top     Avery Bradley  New Orleans Pelicans         NaN       SG         NaN
freq                1                    19         NaN      102         NaN
mean              NaN                   NaN   17.678337      NaN   26.938731
std               NaN                   NaN   15.966090      NaN    4.404016
min               NaN                   NaN    0.000000      NaN   19.000000
25%               NaN                   NaN    5.000000      NaN   24.000000
50%               NaN                   NaN   13.000000      NaN   26.000000
75%               NaN                   NaN   25.000000      NaN   30.000000
max               NaN                   NaN   99.000000      NaN   40.000000

       Height      Weight   College        Salary
count     457  457.000000       373  4.460000e+02
unique     18         NaN       118           NaN
top       6-9         NaN  Kentucky           NaN
freq       59         NaN        22           NaN
mean      NaN  221.522976       NaN  4.842684e+06
std       NaN   26.368343       NaN  5.229238e+06
min       NaN  161.000000       NaN  3.088800e+04
25%       NaN  200.000000       NaN  1.044792e+06
50%       NaN  220.000000       NaN  2.839073e+06
75%       NaN  240.000000       NaN  6.500000e+06
max       NaN  307.000000       NaN  2.500000e+07

In [128]:
#adding a new column 
data = {'Name': ['Leahile', 'Hontse', 'Botshelo'],
        'Age': [19, 17, 18],
        'Qualification': ['BscIT', 'LLB', 'BCOM']}
df = pd.DataFrame(data)

grades = [90, 89, 75]

df['Grades'] = grades
print(df)

       Name  Age Qualification  Grades
0   Leahile   19         BscIT      90
1    Hontse   17           LLB      89
2  Botshelo   18          BCOM      75

In [138]:
#adding a new column
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv")
data.head(10)
new_row = pd.DataFrame({'Name': 'Gontse', 'Team': 'Boston', 
                                     'Number': 3, 'Position': 'PG', 'Age': 33,
                                     'Height': '5-5', 'Weight': 189, 'College':'MIT',
                                     'Salary':15000000}, index=[0])
data= pd.concat([new_row, data]).reset_index(drop=True)
data.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Gontse,Boston,3.0,PG,33.0,5-5,189.0,MIT,15000000.0
1,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
2,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
4,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0

In [144]:
#deleting row
data = pd.read_csv(r"C:\Users\gonts\Downloads\nba.csv", index_col='Name')
df = pd.DataFrame(data)
df.drop(['Avery Bradley', 'John Holland'], inplace=True)
df.head(5)

,Team,Number,Position,Age,Height,Weight,College,Salary
Name,,,,,,,,
Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0

In [150]:
#Accessing columns from dataframe
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 
        'Age': [25, 30, 22, 35, 28], 
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'], 
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)

age_column = df['Age']
print(age_column)

0    25
1    30
2    22
3    35
4    28
Name: Age, dtype: int64

In [153]:
#Accessing rows by index
second_row = df.iloc[1]
print(second_row)

Name       Alice
Age           30
Gender    Female
Salary     55000
Name: 1, dtype: object

In [155]:
#Accessing multiple rows or columns
name_age = df.loc[0:2, ['Name', 'Age', 'Gender']]
print(name_age)

    Name  Age  Gender
0   John   25    Male
1  Alice   30  Female
2    Bob   22    Male

In [156]:
#Accessing rows based on conditions
filtered_data = df[df['Age'] > 25]
print(filtered_data)

      Name  Age  Gender  Salary
1    Alice   30  Female   55000
3      Eve   35  Female   70000
4  Charlie   28    Male   48000

In [157]:
#Accessing specific cells with at 
salary_index2 = df.at[2, 'Salary']
print(salary_index2)

40000

In [4]:
#Slicing Pandas DataFrame
#Create a custom DataFrame
player_list = [['Leahile', 19, 54, 167000],
            ['Lerato', 18, 60, 122000],
            ['Koketso', 20, 61, 134000],
            ['Lesego', 16, 55, 123000],
            ['Kamo', 21, 65, 150000],
            ['Itumeleng', 19, 63, 250000],
            ['Botshelo', 27, 66, 123400],
            ['Mia', 29, 71, 178900]]

df = pd.DataFrame(player_list, columns=['Name', 'Age', 'weight', 'Salary'])
print(df)

        Name  Age  weight  Salary
0    Leahile   19      54  167000
1     Lerato   18      60  122000
2    Koketso   20      61  134000
3     Lesego   20      55  123000
4       Kamo   21      65  150000
5  Itumeleng   19      63  250000
6   Botshelo   27      66  123400
7        Mia   29      71  178900

In [7]:
#Using boolean conditions in pandas dataframe
data = df[df['Age'] >= 18 ].iloc[:, :]
data_count = df[df['Age'] >=18].count()
print(data)
print("Number of people older than or equal to 18 yrs:\n", data_count)

        Name  Age  weight  Salary
0    Leahile   19      54  167000
1     Lerato   18      60  122000
2    Koketso   20      61  134000
3     Lesego   20      55  123000
4       Kamo   21      65  150000
5  Itumeleng   19      63  250000
6   Botshelo   27      66  123400
7        Mia   29      71  178900
Number of people older than or equal to 18 yrs:
 Name      8
Age       8
weight    8
Salary    8
dtype: int64

In [8]:
#Slicing usin loc[]
df.set_index('Name', inplace=True)

custom = df.loc['Leahile': 'Kamo']
print(custom)

         Age  weight  Salary
Name
Leahile   19      54  167000
Lerato    18      60  122000
Koketso   20      61  134000
Lesego    20      55  123000
Kamo      21      65  150000

In [9]:
#selecting specified cell in dataframe
value = df.loc['Itumeleng', 'Salary']
print("Value of Itu's salary:\n", value)

Value of Itu's salary:
 250000

In [10]:
#Sorting pandas dataframe
#sorting a dataframe by a single column
data = {'Name': ['Leahile', 'Koketso', 'Botshelo', 'Mia'],
        'Age': [25, 32, 27, 21],
        'Score': [85, 90, 79, 78]}

df = pd.DataFrame(data)
sorted_df = df.sort_values(by='Age', ascending=False)
print(sorted_df)

       Name  Age  Score
1   Koketso   32     90
2  Botshelo   27     79
0   Leahile   25     85
3       Mia   21     78

In [12]:
#sorting a dataframe by multiple columns
sorted_df = df.sort_values(by=['Age', 'Score'], ascending=False)
print(sorted_df)

       Name  Age  Score
1   Koketso   32     90
2  Botshelo   27     79
0   Leahile   25     85
3       Mia   21     78

In [15]:
#sorting dataframe with missing values
data = {'Name': ['Leahile', 'Koketso', 'Botshelo', 'Mia'],
        'Age': [25, None, 27, 21],
        'Score': [85, 90, None, 78]}

df = pd.DataFrame(data)
sorted_nan = df.sort_values(by="Age", na_position="first")
print(sorted_nan)

       Name   Age  Score
1   Koketso   NaN   90.0
3       Mia  21.0   78.0
0   Leahile  25.0   85.0
2  Botshelo  27.0    NaN

In [20]:
#removing duplicates in pandas dataframe
player_list = [['Leahile', 19, 54, 167000],
            ['Lerato', 18, 60, 122000],
            ['Koketso', 20, 61, 134000],
            ['Leahile', 19, 54, 167000],
            ['Lesego', 16, 55, 123000],
            ['Kamo', 21, 65, 150000],
            ['Itumeleng', 19, 63, 250000],
            ['Botshelo', 27, 66, 123400],
            ['Mia', 29, 71, 178900],
            ['Kamo', 21, 65, 150000]]

df = pd.DataFrame(player_list)
print("Original Dataframe:\n", df)

print("\n")

df_cleaned = df.drop_duplicates()
print("Modified Dataframe (no duplicates):\n", df_cleaned)

Original Dataframe:
            0   1   2       3
0    Leahile  19  54  167000
1     Lerato  18  60  122000
2    Koketso  20  61  134000
3    Leahile  19  54  167000
4     Lesego  16  55  123000
5       Kamo  21  65  150000
6  Itumeleng  19  63  250000
7   Botshelo  27  66  123400
8        Mia  29  71  178900
9       Kamo  21  65  150000


Modified Dataframe (no duplicates):
            0   1   2       3
0    Leahile  19  54  167000
1     Lerato  18  60  122000
2    Koketso  20  61  134000
4     Lesego  16  55  123000
5       Kamo  21  65  150000
6  Itumeleng  19  63  250000
7   Botshelo  27  66  123400
8        Mia  29  71  178900

In [21]:
#dropping duplicates based on specific columns

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Alice', 'David'],
    'Age': [25, 30, 25, 40],
    'City': ['NY', 'LA', 'SF', 'Chicago']
})

df_cleaned = df.drop_duplicates(subset=["Name"])

print(df_cleaned)

    Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

In [23]:
#dropping all duplicates
import pandas as pd

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Alice', 'David'],
    'Age': [25, 30, 25, 40],
    'City': ['NY', 'LA', 'NY', 'Chicago']
})

df_cleaned = df.drop_duplicates(keep=False)

print(df_cleaned)

    Name  Age     City
1    Bob   30       LA
3  David   40  Chicago

In [24]:
#changing pandas data type using astype() method

data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 
        'Age': [25, 30, 22, 35, 28], 
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male'], 
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)

# Convert 'Age' column to float type
df['Age'] = df['Age'].astype(float)
print(df.dtypes)

Name       object
Age       float64
Gender     object
Salary      int64
dtype: object

In [27]:
#drop empty columns in pandas
#create a sample dataframe
df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],
                            "Gender": ["", "", ""],
                            "Age": [0, 0, 0]})
df['Department'] = np.nan

display(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

In [29]:
#remove all null value columns
df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'],
                            "Gender": ["", "", ""],
                            "Age": [0, 0, 0]})

df['Department'] = np.nan

display(df)

df.dropna(how='all', axis=1, inplace=True)

display(df)

  FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

  FirstName Gender  Age
0     Vipul           0
1    Ashish           0
2     Milan           0

In [34]:
#replace both zeros and empty strings with null and drop null columns
df = pd.DataFrame({'Name': ['Damon', 'Stefan', 'Caroline', 'Klaus'],
                   'Trait': ['', '', '', ''],
                   'Age': [0, 0, 0, 0]})

df['Position'] = np.nan
display(df)

nan_value = "NaN"
df.replace(0, nan_value, inplace=True)
df.replace('', nan_value, inplace=True)

df.dropna(how='all', axis=1, inplace=True)
display(df)

       Name Trait  Age  Position
0     Damon          0       NaN
1    Stefan          0       NaN
2  Caroline          0       NaN
3     Klaus          0       NaN

       Name Trait  Age
0     Damon   NaN  NaN
1    Stefan   NaN  NaN
2  Caroline   NaN  NaN
3     Klaus   NaN  NaN